import type { Dish, Order, Reservation, Table } from "./types";

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`;

export const SEED_DISHES: Dish[] = [
  {
    id: "d1",
    name: "Wagyu Tartare",
    description: "Hand-cut A5 wagyu, smoked yolk, black truffle, sourdough crisp.",
    price: 38,
    category: "starters",
    image: img("1544025162-d76694265947"),
    calories: 320,
    prepTime: 12,
    badges: ["chef", "exclusive"],
    available: true,
  },
  {
    id: "d2",
    name: "Burrata d'Andria",
    description: "Heirloom tomato, basil oil, aged balsamic pearls, sea salt.",
    price: 22,
    category: "starters",
    image: img("1565299624946-b28f40a0ae38"),
    calories: 280,
    prepTime: 8,
    badges: ["bestseller"],
    available: true,
  },
  {
    id: "d3",
    name: "Hokkaido Scallops",
    description: "Seared scallops, brown butter, cauliflower velouté, Oscietra caviar.",
    price: 42,
    category: "starters",
    image: img("1599487488170-d11ec9c172f0"),
    calories: 240,
    prepTime: 14,
    badges: ["vip", "limited"],
    available: true,
  },
  {
    id: "d4",
    name: "Dry-Aged Ribeye",
    description: "45-day dry-aged ribeye, bone marrow jus, charred shallot.",
    price: 78,
    category: "mains",
    image: img("1546964124-0cce460f38ef"),
    calories: 820,
    prepTime: 25,
    badges: ["bestseller", "chef"],
    available: true,
  },
  {
    id: "d5",
    name: "Black Cod Miso",
    description: "Saikyo miso glaze, pickled ginger, yuzu emulsion.",
    price: 56,
    category: "mains",
    image: img("1519708227418-c8fd9a32b7a2"),
    calories: 480,
    prepTime: 22,
    badges: ["new"],
    available: true,
  },
  {
    id: "d6",
    name: "Truffle Risotto",
    description: "Carnaroli, aged parmesan, fresh shaved Alba truffle.",
    price: 64,
    category: "mains",
    image: img("1476124369491-e7addf5db371"),
    calories: 720,
    prepTime: 20,
    badges: ["vip", "exclusive"],
    available: true,
  },
  {
    id: "d7",
    name: "Lamb Saddle",
    description: "Herb-crusted saddle, smoked aubergine, jus de viande.",
    price: 62,
    category: "mains",
    image: img("1514516816566-de580c621376"),
    calories: 680,
    prepTime: 28,
    badges: ["spicy"],
    available: true,
  },
  {
    id: "d8",
    name: "Valrhona Soufflé",
    description: "Warm 70% chocolate, salted caramel core, gold leaf.",
    price: 24,
    category: "desserts",
    image: img("1606313564200-e75d5e30476c"),
    calories: 540,
    prepTime: 18,
    badges: ["chef", "bestseller"],
    available: true,
  },
  {
    id: "d9",
    name: "Vanilla Mille-Feuille",
    description: "Madagascar vanilla cream, caramelised puff, raspberry coulis.",
    price: 19,
    category: "desserts",
    image: img("1488477181946-6428a0291777"),
    calories: 460,
    prepTime: 10,
    badges: ["new"],
    available: true,
  },
  {
    id: "d10",
    name: "Cheese Trolley",
    description: "Five aged French & Italian cheeses, fig jam, walnut bread.",
    price: 32,
    category: "desserts",
    image: img("1486297678162-eb2a19b0a32d"),
    calories: 620,
    badges: ["limited"],
    available: true,
  },
  {
    id: "d11",
    name: "Vintage Champagne",
    description: "Dom Pérignon 2013, served in chilled crystal flute.",
    price: 95,
    category: "drinks",
    image: img("1551024709-8f23befc6f87"),
    badges: ["vip", "exclusive"],
    available: true,
  },
  {
    id: "d12",
    name: "Smoked Old Fashioned",
    description: "Yamazaki 12, applewood smoke, demerara, orange bitters.",
    price: 28,
    category: "drinks",
    image: img("1514362545857-3bc16c4c7d1b"),
    badges: ["bestseller"],
    available: true,
  },
  {
    id: "d13",
    name: "Garden Negroni",
    description: "House gin, Campari, sweet vermouth, rosemary smoke.",
    price: 22,
    category: "drinks",
    image: img("1514362545857-3bc16c4c7d1b"),
    badges: ["new"],
    available: true,
  },
  {
    id: "d14",
    name: "Omakase Tasting",
    description: "Seven-course chef's journey through tonight's market.",
    price: 245,
    category: "specials",
    image: img("1540189549336-e6e99c3679fe"),
    prepTime: 90,
    badges: ["vip", "chef", "limited"],
    available: true,
  },
  {
    id: "d15",
    name: "White Truffle Tagliolini",
    description: "Fresh egg pasta, butter emulsion, 8g shaved white truffle.",
    price: 120,
    category: "specials",
    image: img("1473093295043-cdd812d0e601"),
    badges: ["exclusive", "limited", "discount"],
    available: true,
  },
];

export const SEED_TABLES: Table[] = [
  { id: "1", name: "Table 1", seats: 2, active: true },
  { id: "2", name: "Table 2", seats: 2, active: true },
  { id: "3", name: "Table 3", seats: 4, active: true },
  { id: "4", name: "Table 4", seats: 4, active: true },
  { id: "5", name: "Table 5", seats: 6, active: true },
  { id: "VIP1", name: "VIP Suite 1", seats: 8, active: true },
  { id: "VIP2", name: "VIP Suite 2", seats: 10, active: true },
];

const now = Date.now();
export const SEED_ORDERS: Order[] = [
  {
    id: "o1",
    table: "3",
    items: [
      { dish: SEED_DISHES[3], qty: 2 },
      { dish: SEED_DISHES[7], qty: 2, notes: "Extra caramel" },
    ],
    subtotal: 204,
    service: 20.4,
    tax: 16.32,
    total: 240.72,
    status: "preparing",
    createdAt: now - 1000 * 60 * 8,
  },
  {
    id: "o2",
    table: "VIP1",
    items: [
      { dish: SEED_DISHES[13], qty: 4 },
      { dish: SEED_DISHES[10], qty: 2 },
    ],
    subtotal: 1170,
    service: 117,
    tax: 93.6,
    total: 1380.6,
    status: "new",
    createdAt: now - 1000 * 60 * 2,
  },
  {
    id: "o3",
    table: "5",
    items: [{ dish: SEED_DISHES[5], qty: 3 }],
    subtotal: 192,
    service: 19.2,
    tax: 15.36,
    total: 226.56,
    status: "ready",
    createdAt: now - 1000 * 60 * 18,
  },
];

export const SEED_RESERVATIONS: Reservation[] = [
  {
    id: "r1",
    name: "Mr. Laurent",
    phone: "+33 6 12 34 56 78",
    guests: 4,
    date: new Date(now + 86400000).toISOString().slice(0, 10),
    time: "20:00",
    notes: "Anniversary",
    createdAt: now - 1000 * 60 * 60 * 4,
  },
];
